### ISSUE TITLE
Mixed Content

### ISSUE THREAD

**Issue by ValeTheVioletMote** [centricconsulting/qrcode-api#3]
Content from this service is rejected if the page requesting is in https.
`Blocked loading mixed active content “http://qrcode.centri.cc:3022/encode”`
 Possible to let the service work for https as well?

Application currently fails to respond to POSTs made toward **https**://qrcode.centri.cc:3022/encode

**Comment by wjklos** [comment]
Created a self-signed cert and implemented TLS.
